name: Generate profile summary cards

on:
  schedule:
    - cron: "17 3 * * *" # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          theme: "2077"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
